services:
  db:
    image: mysql:8.0
    container_name: movietheater-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$$MYSQL_PASSWORD mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    container_name: movietheater-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: movietheater-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000/api

volumes:
  mysql_data: